steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/games-483513/speech-backend:latest
      - --destination=gcr.io/games-483513/speech-backend:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=720h
options:
  machineType: 'E2_HIGHMEM_8'
timeout: 1800s
